FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN wget -qO- https://github.com/hakimel/reveal.js/archive/3.8.0.tar.gz | tar xvz -C /tmp
RUN mv /tmp/reveal.js-3.8.0/* .
COPY index.html .
COPY KeyNote.md .
COPY res/ res/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]